from pathlib import Path
p=Path('app/src/main/java/com/hokkaidogolf/trip/FieldGpsV09Activity.java')
s=p.read_text()
if 'V1.13.6 · ROUND LOG' not in s: raise SystemExit('ui tune requires V1.13.6 ROUND LOG')

def repl_method(src,sig,new):
    a=src.find(sig)
    if a<0: raise SystemExit('missing method '+sig)
    b=src.find('{',a); dep=0; ins=False; inc=False; esc=False; i=b
    while i<len(src):
        ch=src[i]
        if esc: esc=False
        elif ch=='\\' and (ins or inc): esc=True
        elif ch=='"' and not inc: ins=not ins
        elif ch=="'" and not ins: inc=not inc
        elif not ins and not inc:
            if ch=='{': dep+=1
            elif ch=='}':
                dep-=1
                if dep==0: return src[:a]+new+src[i+1:]
        i+=1
    raise SystemExit('unterminated '+sig)

if 'import android.location.GnssStatus;' not in s:s=s.replace('import android.location.LocationManager;','import android.location.LocationManager;\nimport android.location.GnssStatus;',1)
if 'import android.os.Handler;' not in s:s=s.replace('import android.os.SystemClock;','import android.os.SystemClock;\nimport android.os.Handler;\nimport android.os.Looper;',1)
if 'import java.net.HttpURLConnection;' not in s:
    m='public class FieldGpsV09Activity';i=s.find(m);s=s[:i]+'import java.io.BufferedReader;\nimport java.io.InputStreamReader;\nimport java.net.HttpURLConnection;\nimport java.net.URL;\nimport java.util.Locale;\n\n'+s[i:]

f='    private GolfView view;'
if 'gnssCallbackUiTuneV1136' not in s:s=s.replace(f,f+'\n    private GnssStatus.Callback gnssCallbackUiTuneV1136;\n    private boolean gnssRegisteredUiTuneV1136=false;',1)

s=repl_method(s,'    private void startGps()',r'''    private void startGps() {
        if(lm==null||checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;
        try{lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,700,0.6f,this);}catch(Exception ignored){}
        try{
            if(gnssCallbackUiTuneV1136==null)gnssCallbackUiTuneV1136=new GnssStatus.Callback(){@Override public void onSatelliteStatusChanged(GnssStatus st){int used=0,seen=st.getSatelliteCount();float sum=0f;for(int i=0;i<seen;i++)if(st.usedInFix(i)){used++;sum+=st.getCn0DbHz(i);}if(view!=null)view.setGnssUiTuneV1136(used,seen,used>0?sum/used:0f);}};
            if(!gnssRegisteredUiTuneV1136){lm.registerGnssStatusCallback(gnssCallbackUiTuneV1136,new Handler(Looper.getMainLooper()));gnssRegisteredUiTuneV1136=true;}
        }catch(Exception ignored){}
    }''')
s=repl_method(s,'    @Override protected void onPause()',r'''    @Override protected void onPause(){super.onPause();try{if(lm!=null)lm.removeUpdates(this);}catch(Exception ignored){}try{if(lm!=null&&gnssRegisteredUiTuneV1136&&gnssCallbackUiTuneV1136!=null)lm.unregisterGnssStatusCallback(gnssCallbackUiTuneV1136);}catch(Exception ignored){}gnssRegisteredUiTuneV1136=false;}''')

f='        private Location location;'
if 'UI_TUNE_R1_V1136' not in s:s=s.replace(f,f+'''\n        private volatile int gpsUsedUiTuneV1136=0,gpsSeenUiTuneV1136=0;\n        private volatile float gpsCn0UiTuneV1136=0f;\n        private volatile float weatherTempUiTuneV1136=Float.NaN,weatherWindMsUiTuneV1136=Float.NaN,weatherWindDegUiTuneV1136=Float.NaN;\n        private volatile int weatherCodeUiTuneV1136=-1;\n        private volatile long weatherAttemptUiTuneV1136=0L;\n        private static final String UI_TUNE_R1_V1136="V1.13.6_UI_TUNE_R1";''',1)
a='            location=l; lastFixElapsed=SystemClock.elapsedRealtime();'
if 'maybeFetchWeatherUiTuneV1136(l);' not in s:s=s.replace(a,a+'\n            maybeFetchWeatherUiTuneV1136(l);',1)

anchor='        private void saveState(){';i=s.find(anchor)
helpers=r'''        void setGnssUiTuneV1136(int used,int seen,float cn0){gpsUsedUiTuneV1136=Math.max(0,used);gpsSeenUiTuneV1136=Math.max(0,seen);gpsCn0UiTuneV1136=Math.max(0f,cn0);invalidate();}
        private int gpsBarsUiTuneV1136(){if(gpsUsedUiTuneV1136>0){if(gpsUsedUiTuneV1136>=10&&gpsCn0UiTuneV1136>=28f)return 4;if(gpsUsedUiTuneV1136>=7&&gpsCn0UiTuneV1136>=23f)return 3;if(gpsUsedUiTuneV1136>=4)return 2;return 1;}if(location==null)return 0;float a=location.getAccuracy();return a<=8?4:(a<=15?3:(a<=25?2:1));}
        private void maybeFetchWeatherUiTuneV1136(Location l){if(l==null)return;long now=SystemClock.elapsedRealtime();if(now-weatherAttemptUiTuneV1136<600000L)return;weatherAttemptUiTuneV1136=now;final double lat=l.getLatitude(),lon=l.getLongitude();new Thread(()->{HttpURLConnection con=null;try{String q=String.format(Locale.US,"https://api.open-meteo.com/v1/forecast?latitude=%.5f&longitude=%.5f&current=temperature_2m,weather_code,wind_speed_10m,wind_direction_10m&wind_speed_unit=ms&timezone=auto",lat,lon);con=(HttpURLConnection)new URL(q).openConnection();con.setConnectTimeout(4500);con.setReadTimeout(4500);BufferedReader br=new BufferedReader(new InputStreamReader(con.getInputStream()));StringBuilder sb=new StringBuilder();String ln;while((ln=br.readLine())!=null)sb.append(ln);br.close();String j=sb.toString();float t=jsonNumUiTuneV1136(j,"temperature_2m"),ws=jsonNumUiTuneV1136(j,"wind_speed_10m"),wd=jsonNumUiTuneV1136(j,"wind_direction_10m"),wc=jsonNumUiTuneV1136(j,"weather_code");if(!Float.isNaN(t))weatherTempUiTuneV1136=t;if(!Float.isNaN(ws))weatherWindMsUiTuneV1136=ws;if(!Float.isNaN(wd))weatherWindDegUiTuneV1136=wd;if(!Float.isNaN(wc))weatherCodeUiTuneV1136=Math.round(wc);post(()->invalidate());}catch(Exception ignored){}finally{if(con!=null)con.disconnect();}},"field-weather").start();}
        private float jsonNumUiTuneV1136(String j,String k){try{java.util.regex.Matcher m=java.util.regex.Pattern.compile("\\\""+java.util.regex.Pattern.quote(k)+"\\\"\\s*:\\s*(-?\\d+(?:\\.\\d+)?)").matcher(j);return m.find()?Float.parseFloat(m.group(1)):Float.NaN;}catch(Exception e){return Float.NaN;}}
        private String windDirUiTuneV1136(){if(Float.isNaN(weatherWindDegUiTuneV1136))return "--";String[] d={"N","NE","E","SE","S","SW","W","NW"};return d[Math.round(weatherWindDegUiTuneV1136/45f)&7];}
        private String weatherTextUiTuneV1136(){int c=weatherCodeUiTuneV1136;if(c<0)return "날씨";if(c==0)return "맑음";if(c<=3)return "구름";if(c==45||c==48)return "안개";if((c>=51&&c<=67)||(c>=80&&c<=82))return "비";if((c>=71&&c<=77)||(c>=85&&c<=86))return "눈";if(c>=95)return "뇌우";return "날씨";}
        private void drawWeatherIconUiTuneV1136(Canvas c,float x,float y,float r){int code=weatherCodeUiTuneV1136;boolean rain=(code>=51&&code<=67)||(code>=80&&code<=82)||code>=95,snow=(code>=71&&code<=77)||(code>=85&&code<=86),cloudy=code>0;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(Math.max(2f,r*.10f));p.setColor(Color.rgb(244,178,42));float sx=x-r*.28f,sy=y-r*.18f,sr=r*.28f;c.drawCircle(sx,sy,sr,p);for(int n=0;n<8;n++){double a=n*Math.PI/4;c.drawLine(sx+(float)Math.cos(a)*sr*1.25f,sy+(float)Math.sin(a)*sr*1.25f,sx+(float)Math.cos(a)*sr*1.55f,sy+(float)Math.sin(a)*sr*1.55f,p);}p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(255,205,66));c.drawCircle(sx,sy,sr*.82f,p);if(cloudy){p.setColor(Color.rgb(250,253,248));c.drawCircle(x-r*.08f,y,r*.28f,p);c.drawCircle(x+r*.18f,y-r*.06f,r*.23f,p);c.drawCircle(x+r*.37f,y+r*.02f,r*.18f,p);c.drawRoundRect(new RectF(x-r*.16f,y,x+r*.52f,y+r*.22f),r*.11f,r*.11f,p);}if(rain||snow){p.setColor(rain?Color.rgb(73,181,237):Color.WHITE);for(int n=0;n<3;n++){float dx=x-r*.02f+n*r*.22f;if(rain)c.drawRoundRect(new RectF(dx,y+r*.30f,dx+r*.06f,y+r*.48f),r*.03f,r*.03f,p);else c.drawCircle(dx,y+r*.39f,r*.055f,p);}}}
        private void drawFieldConditionUiTuneV1136(Canvas c,float w,float h){RectF card=new RectF(w*.595f,h*.006f,w*.965f,h*.066f);p.setColor(Color.rgb(253,254,247));c.drawRoundRect(card,card.height()*.30f,card.height()*.30f,p);float ir=card.height()*.31f;drawWeatherIconUiTuneV1136(c,card.left+ir*1.35f,card.top+card.height()*.37f,ir);String temp=Float.isNaN(weatherTempUiTuneV1136)?"--°":Math.round(weatherTempUiTuneV1136)+"°";text(c,temp,card.left+card.width()*.24f,card.top+card.height()*.37f,14f,INK,true);text(c,weatherTextUiTuneV1136(),card.left+card.width()*.38f,card.top+card.height()*.35f,7.2f,Color.rgb(83,112,83),true);String wind=windDirUiTuneV1136()+"  "+(Float.isNaN(weatherWindMsUiTuneV1136)?"--":String.format(Locale.US,"%.1f",weatherWindMsUiTuneV1136))+" m/s";text(c,wind,card.left+card.width()*.14f,card.bottom-card.height()*.15f,11.8f,INK,true);text(c,"GPS",card.left+card.width()*.69f,card.top+card.height()*.28f,11.8f,DEEP,true);int bars=gpsBarsUiTuneV1136();float bx=card.left+card.width()*.84f,base=card.top+card.height()*.37f,bw=card.width()*.018f,gap=bw*.65f;for(int n=0;n<4;n++){float bh=card.height()*(.10f+.065f*n);p.setColor(n<bars?Color.rgb(54,164,97):Color.rgb(204,220,205));c.drawRoundRect(new RectF(bx+n*(bw+gap),base-bh,bx+n*(bw+gap)+bw,base),bw*.35f,bw*.35f,p);}text(c,gpsUsedUiTuneV1136>0?gpsUsedUiTuneV1136+" SAT":(bars>0?"SIGNAL":"WAIT"),card.left+card.width()*.71f,card.bottom-card.height()*.15f,8f,bars>=3?GREEN:(bars>0?AMBER:CORAL),true);}
        private void drawMetricUiTuneV1136(Canvas c,String lab,String val,float x,RectF bar){text(c,lab,x,bar.top+bar.height()*.31f,13.2f,Color.WHITE,true,Paint.Align.CENTER);text(c,val,x,bar.bottom-getHeight()*.0085f,20f,Color.WHITE,true,Paint.Align.CENTER);}
        private void premiumBoxUiTuneV1136(Canvas c,RectF b,String lab,String val,boolean wide){RectF sh=new RectF(b.left+3,b.top+5,b.right+3,b.bottom+5);p.setColor(Color.argb(30,90,70,30));c.drawRoundRect(sh,18,18,p);p.setColor(Color.rgb(255,252,239));c.drawRoundRect(b,18,18,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3f);p.setColor(Color.rgb(205,159,55));c.drawRoundRect(b,18,18,p);p.setStyle(Paint.Style.FILL);text(c,lab,b.centerX(),b.top+b.height()*.27f,5.9f,Color.rgb(139,99,28),true,Paint.Align.CENTER);text(c,val,b.centerX(),b.bottom-b.height()*.14f,wide?22f:21f,DEEP,true,Paint.Align.CENTER);}
        private void drawPremiumInfoUiTuneV1136(Canvas c,RectF r,int par){float x=r.left+r.width()*.018f,y=r.top+r.height()*.078f,g=r.width()*.012f,av=r.width()*.245f,pw=av*.405f,hw=av-pw-g,hh=Math.min(r.height()*.102f,getHeight()*.064f);premiumBoxUiTuneV1136(c,new RectF(x,y,x+hw,y+hh),"HOLE","H"+hole,true);x+=hw+g;premiumBoxUiTuneV1136(c,new RectF(x,y,x+pw,y+hh),"PAR",""+par,false);}
        private void bigActionUiTuneV1136(Canvas c,RectF b,int bg,String lab,int fg){RectF sh=new RectF(b.left,b.top+4,b.right,b.bottom+4);p.setColor(Color.argb(24,30,65,40));c.drawRoundRect(sh,b.height()*.34f,b.height()*.34f,p);p.setColor(bg);c.drawRoundRect(b,b.height()*.34f,b.height()*.34f,p);text(c,lab,b.centerX(),b.centerY()+b.height()*.12f,14.5f,fg,true,Paint.Align.CENTER);}
        private void storyNavUiTuneV1136(Canvas c,RectF b,int k,boolean on){int[] bg={Color.rgb(255,240,218),Color.rgb(225,247,219),Color.rgb(223,242,252),Color.rgb(242,229,249),Color.rgb(255,240,203)};p.setColor(bg[k]);c.drawRoundRect(b,18,18,p);RectF sky=new RectF(b.left+5,b.top+5,b.right-5,b.top+b.height()*.50f);p.setColor(Color.rgb(219,244,252));c.drawRoundRect(sky,13,13,p);p.setColor(Color.rgb(153,211,116));c.drawOval(new RectF(b.left-4,b.top+b.height()*.43f,b.centerX()+12,b.bottom+12),p);p.setColor(Color.rgb(105,184,88));c.drawOval(new RectF(b.centerX()-7,b.top+b.height()*.40f,b.right+8,b.bottom+12),p);float cx=b.centerX(),cy=b.top+b.height()*.57f;if(k==0){p.setColor(Color.rgb(238,112,98));Path q=new Path();q.moveTo(cx-19,cy);q.lineTo(cx,cy-17);q.lineTo(cx+19,cy);q.close();c.drawPath(q,p);p.setColor(Color.rgb(255,248,225));c.drawRoundRect(new RectF(cx-15,cy,cx+15,cy+19),4,4,p);}else if(k==1){p.setColor(DEEP);c.drawRect(cx-2,cy-18,cx+2,cy+19,p);p.setColor(Color.rgb(238,112,98));Path q=new Path();q.moveTo(cx+2,cy-18);q.lineTo(cx+22,cy-12);q.lineTo(cx+2,cy-6);q.close();c.drawPath(q,p);p.setColor(Color.WHITE);c.drawCircle(cx-22,cy+13,8,p);}else if(k==2){p.setColor(Color.rgb(255,253,241));c.drawRoundRect(new RectF(cx-23,cy-16,cx+14,cy+18),6,6,p);p.setColor(Color.rgb(244,174,88));c.save();c.rotate(-45,cx+10,cy);c.drawRoundRect(new RectF(cx+7,cy-18,cx+13,cy+22),3,3,p);c.restore();}else if(k==3){p.setColor(Color.rgb(255,253,241));c.drawRoundRect(new RectF(cx-24,cy-16,cx+24,cy+18),6,6,p);p.setColor(Color.rgb(145,117,173));for(int n=0;n<3;n++){float yy=cy-8+n*9;c.drawCircle(cx-15,yy,3,p);c.drawRoundRect(new RectF(cx-7,yy-1,cx+15,yy+1),1,1,p);}}else{p.setColor(Color.rgb(255,225,135));c.drawRoundRect(new RectF(cx-13,cy-14,cx+13,cy+5),5,5,p);p.setColor(Color.rgb(210,161,55));c.drawRect(cx-3,cy+5,cx+3,cy+15,p);c.drawRoundRect(new RectF(cx-14,cy+14,cx+14,cy+19),3,3,p);}if(on){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3f);p.setColor(Color.rgb(118,192,133));c.drawRoundRect(b,18,18,p);p.setStyle(Paint.Style.FILL);}}

'''
s=s[:i]+helpers+s[i:]

s=repl_method(s,'        private void drawFullHoleYardageV1102(',r'''        private void drawFullHoleYardageV1102(Canvas c,RectF r,int par,int totalM){Bitmap b=fullHoleBitmapV1102();if(b==null){if(selected==3){drawNaepoFieldCanvasV1131(c,r,par,totalM);return;}drawActualYardageV190(c,r,par,totalM);return;}softShadow(c,r,28);box(c,r,Color.rgb(242,248,223),28);RectF art=new RectF(r.left+r.width()*.285f,r.top+r.height()*.060f,r.right-r.width()*.255f,r.bottom-r.height()*.055f);RectF dst=fitCenterV1102(b,art);Paint bp=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);c.drawBitmap(b,null,dst,bp);RectF gt=new RectF(r.left+10,r.top+8,r.left+82,r.top+42);box(c,gt,DEEP,17);text(c,"GREEN",gt.centerX(),gt.centerY()+4,7.5f,Color.WHITE,true,Paint.Align.CENTER);RectF tt=new RectF(r.left+10,r.bottom-46,r.left+68,r.bottom-12);box(c,tt,DEEP,17);text(c,"TEE",tt.centerX(),tt.centerY()+4,7.5f,Color.WHITE,true,Paint.Align.CENTER);drawPremiumInfoUiTuneV1136(c,r,par);int max=Math.max(100,totalM);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.6f);p.setColor(Color.argb(145,55,86,62));for(int d=50;d<max;d+=50){float y=dst.bottom-d/(float)max*dst.height(),x2=r.right-10,x1=x2-17;c.drawLine(x1,y,x2,y,p);text(c,d+"m",x1-8,y+5,13.7f,Color.rgb(55,86,62),true,Paint.Align.RIGHT);}p.setStyle(Paint.Style.FILL);text(c,"TEE 0",r.right-12,r.top+24,5.8f,AMBER,true,Paint.Align.RIGHT);drawFieldNavV1110(c,art,totalM);String src=selected==4?"ROYAL LINKS OFFICIAL FULL HOLE":"PRINCE OFFICIAL FULL HOLE";textFit(c,src+" · TEE → GREEN",r.left+12,r.bottom-4,r.right-12,5.6f,GREEN,true);}''')
s=repl_method(s,'        private void drawHoleStepButtonsV1124(',r'''        private void drawHoleStepButtonsV1124(Canvas c,RectF bar){float w=getWidth(),cy=bar.centerY(),r=Math.min(bar.height()*.43f,w*.048f),lx=bar.left+r+5,rx=bar.right-r-5;holePrevTopV1124.set(lx-r,cy-r,lx+r,cy+r);holeNextTopV1124.set(rx-r,cy-r,rx+r,cy+r);drawHoleStepButtonV1124(c,lx,cy,r,-1,hole>1);drawHoleStepButtonV1124(c,rx,cy,r,1,hole<18);}''')
s=repl_method(s,'        private void drawHoleStepButtonV1124(',r'''        private void drawHoleStepButtonV1124(Canvas c,float x,float y,float r,int dir,boolean en){p.setColor(Color.argb(en?250:90,255,255,255));c.drawCircle(x,y,r,p);p.setStyle(Paint.Style.STROKE);p.setStrokeCap(Paint.Cap.ROUND);p.setStrokeJoin(Paint.Join.ROUND);p.setStrokeWidth(Math.max(4f,r*.13f));p.setColor(Color.argb(en?244:88,8,79,52));c.drawCircle(x,y,r-1.5f,p);float sh=r*.54f,hd=r*.35f,fr=x-dir*sh*.45f,to=x+dir*sh*.52f;c.drawLine(fr,y,to,y,p);c.drawLine(to,y,to-dir*hd,y-hd,p);c.drawLine(to,y,to-dir*hd,y+hd,p);p.setStyle(Paint.Style.FILL);p.setStrokeCap(Paint.Cap.BUTT);p.setStrokeJoin(Paint.Join.MITER);}''')
s=repl_method(s,'        private void roundUnifiedYardageV190(',r'''        private void roundUnifiedYardageV190(Canvas c){float w=getWidth(),h=getHeight(),m=w*.038f;int par=currentPar(),totalM=verifiedMetersV190();c.drawColor(BG);RectF head=new RectF(0,0,w,h*.070f);gradient(c,head,Color.rgb(48,164,229),Color.rgb(91,190,228),0);text(c,ko[selected],m,h*.027f,14.8f,Color.WHITE,true);text(c,variants[selected][variant],m,h*.058f,15.8f,Color.rgb(255,241,190),true);drawFieldConditionUiTuneV1136(c,w,h);RectF range=new RectF(m,h*.071f,w-m,h*.138f);gradient(c,range,Color.rgb(34,126,72),Color.rgb(87,159,98),18);sheen(c,range,18);drawHoleStepButtonsV1124(c,range);int nr=navRemainV1110(totalM);drawMetricUiTuneV1136(c,"TOTAL",totalM>0?totalM+"m":"--",w*.29f,range);drawMetricUiTuneV1136(c,"DIST",(nr>=0?nr:totalM)+"m",w*.51f,range);drawMetricUiTuneV1136(c,"PAR",""+par,w*.72f,range);courseRect.set(m,h*.145f,w-m,h*.836f);drawFullHoleYardageV1102(c,courseRect,par,totalM);boolean ready=previewMode||(location!=null&&location.getAccuracy()<=(selected==3?25:18)&&fixAgeSec()<=15);GeoRef green=greenCenterRef(hole);int gb=ready?(green==null?Color.rgb(161,172,159):DEEP):Color.rgb(161,172,159),tb=ready?(getRef("t",hole)==null?Color.rgb(161,172,159):DEEP):Color.rgb(161,172,159);float gap=w*.012f,usable=w-2*m-2*gap,bw=usable/3f;greenSave.set(m,h*.844f,m+bw,h*.903f);teeSave.set(m+bw+gap,h*.844f,m+2*bw+gap,h*.903f);mapLaunch.set(m+2*bw+2*gap,h*.844f,w-m,h*.903f);bigActionUiTuneV1136(c,greenSave,gb,"GREEN CENTER",Color.WHITE);bigActionUiTuneV1136(c,teeSave,tb,"TEE 저장",Color.WHITE);bigActionUiTuneV1136(c,mapLaunch,CARD,"외부 지도",INK);setFourNav(w,h);drawGoldenNav(c);}''')
s=repl_method(s,'        private void setFourNav(',r'''        private void setFourNav(float w,float h){float l=w*.025f,r=w*.975f,g=w*.004f,ww=(r-l-g*4)/5f;homeBtn.set(l,h*.909f,l+ww,h*.993f);mapTab.set(l+(ww+g),h*.909f,l+(ww+g)+ww,h*.993f);prev.set(l+2*(ww+g),h*.909f,l+2*(ww+g)+ww,h*.993f);scoreTab.set(l+3*(ww+g),h*.909f,l+3*(ww+g)+ww,h*.993f);next.set(l+4*(ww+g),h*.909f,r,h*.993f);}''')
s=repl_method(s,'        private void drawGoldenNav(',r'''        private void drawGoldenNav(Canvas c){float w=getWidth(),h=getHeight();RectF bar=new RectF(w*.020f,h*.906f,w*.980f,h*.997f);softShadow(c,bar,bar.height()*.28f);box(c,bar,CARD,bar.height()*.28f);RectF[] t={homeBtn,mapTab,prev,scoreTab,next};String[] l={"홈","코스","입력","카드","요약"};int[] sc={0,1,2,3,4};for(int i=0;i<5;i++){boolean on=screen==sc[i];RectF b=new RectF(t[i].centerX()-w*.055f,bar.top+h*.006f,t[i].centerX()+w*.055f,bar.top+h*.044f);storyNavUiTuneV1136(c,b,i,on);text(c,l[i],t[i].centerX(),bar.bottom-h*.010f,26.8f,on?GREEN:INK,true,Paint.Align.CENTER);if(on){p.setColor(GREEN);c.drawRoundRect(new RectF(t[i].centerX()-w*.040f,bar.bottom-h*.0037f,t[i].centerX()+w*.040f,bar.bottom-h*.0012f),4,4,p);}}}''')
p.write_text(s)

m=Path('app/src/main/AndroidManifest.xml');x=m.read_text()
if 'android.permission.INTERNET' not in x:x=x.replace('<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />','<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />\n    <uses-permission android:name="android.permission.INTERNET" />',1)
x=x.replace('@drawable/ic_hokkaido_launcher','@drawable/ic_hokkaido_golf_gps_v1136')
m.write_text(x)
print('applied V1.13.6 UI TUNE R1')
