from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, ImageFilter, ImageEnhance
import numpy as np, base64, io, math

# V1.15.3 Furano KING H1-H3 review lock
# - H1 keeps the approved H1 course asset generated by v1152, but is alpha-tight fit.
# - H2/H3 are reconstructed ONLY from the exact user-approved 408_2.webp / 408_3.webp bytes.
# - Fixed clip rectangle: no course pixel/shadow may touch wood header or bottom navigation.
# - Header is redrawn cleanly to eliminate the old captured-header corruption.
# - No geometry warp/rotation/redraw is permitted.

RES=Path('app/src/main/res/drawable-nodpi')
ASSET=Path('.github/assets/furano-v1152')
W,H=941,1672
SAFE={
    1:(267,365,673,1422),
    2:(302,365,638,1422),
    3:(339,365,601,1422),
}
PAR={1:4,2:3,3:4}
VALS={1:(274,286,298),2:(142,154,166),3:(355,367,379)}

JUA='/tmp/Jua-Regular.ttf'
MPLUS='/tmp/MPLUSRounded1c-ExtraBold.ttf'
def font(sz,jp=False):
    p=MPLUS if jp else JUA
    return ImageFont.truetype(p,sz)

def text(d,xy,s,sz,fill,anchor='mm',stroke=0,stroke_fill=(10,20,16,255),jp=False):
    d.text(xy,s,font=font(sz,jp),fill=fill,anchor=anchor,stroke_width=stroke,stroke_fill=stroke_fill)

def exact_h2():
    raw=base64.b64decode(''.join((ASSET/f'king02.part{i}').read_text().strip() for i in (1,2,3,4)),validate=True)
    im=Image.open(io.BytesIO(raw)).convert('RGBA')
    if im.size!=(127,400): raise SystemExit(f'H2 source size changed: {im.size}')
    return im

def exact_h3():
    raw=base64.b64decode((ASSET/'king03.b64').read_text().strip(),validate=True)
    im=Image.open(io.BytesIO(raw)).convert('RGBA')
    if im.size!=(99,400): raise SystemExit(f'H3 source size changed: {im.size}')
    return im

def isolate_h1():
    # Prince H1 source is the already field-verified geometry. Remove ONLY edge-connected neutral page.
    fp=RES/'yardage_furano_king01.jpg'
    im=Image.open(fp).convert('RGB'); a=np.array(im)
    mx=a.max(2);mn=a.min(2);sat=mx-mn
    bg=(a[:,:,0]>230)&(a[:,:,1]>230)&(a[:,:,2]>216)&(sat<48)
    hh,ww=bg.shape
    seen=np.zeros(bg.shape,np.uint8); stack=[]
    for x in range(ww):
        if bg[0,x]: stack.append((0,x))
        if bg[hh-1,x]: stack.append((hh-1,x))
    for y in range(hh):
        if bg[y,0]: stack.append((y,0))
        if bg[y,ww-1]: stack.append((y,ww-1))
    while stack:
        y,x=stack.pop()
        if x<0 or x>=ww or y<0 or y>=hh or seen[y,x] or not bg[y,x]: continue
        seen[y,x]=1
        stack.extend(((y-1,x),(y+1,x),(y,x-1),(y,x+1)))
    alpha=np.where(seen,0,255).astype(np.uint8)
    out=Image.fromarray(np.dstack([a,alpha]),'RGBA')
    box=out.getchannel('A').getbbox()
    if not box: raise SystemExit('H1 alpha-tight crop failed')
    return out.crop(box)

def alpha_tight(im):
    im=im.convert('RGBA')
    box=im.getchannel('A').getbbox()
    if not box: raise SystemExit('empty approved course image')
    return im.crop(box)

def clean_header(base,hole,par):
    # Fully replace 0..155: no pixels from the previous screenshot/captured header survive.
    d=ImageDraw.Draw(base,'RGBA')
    for y in range(0,156):
        t=y/155.0
        col=(int(7+7*t),int(57+51*t),int(151+50*t),255)
        d.line((0,y,W,y),fill=col,width=1)
    # back arrow
    d.line((68,58,41,79),fill='white',width=8)
    d.line((41,79,68,100),fill='white',width=8)
    d.line((42,79,87,79),fill='white',width=8)
    text(d,(97,63),'후라노 골프코스',38,(255,255,255,255),anchor='lm',stroke=2,stroke_fill=(0,42,110,180))
    # small car glyph (simple, deterministic, no unsupported icon font)
    d.rounded_rectangle((39,106,78,132),radius=7,outline=(255,255,255,255),width=4)
    d.line((47,106,54,96),fill='white',width=4);d.line((54,96,72,96),fill='white',width=4);d.line((72,96,78,106),fill='white',width=4)
    d.ellipse((45,128,53,136),fill='white');d.ellipse((67,128,75,136),fill='white')
    text(d,(95,120),f'KING · H{hole} · PAR {par}',27,(255,255,255,255),anchor='lm',stroke=1,stroke_fill=(0,42,110,170),jp=True)
    # weather: stylized sun/cloud, fixed approved presentation
    sx,sy=780,48
    d.ellipse((sx-15,sy-15,sx+15,sy+15),fill=(255,196,20,255))
    for ang in range(0,360,45):
        r=27; x0=sx+math.cos(math.radians(ang))*20; y0=sy+math.sin(math.radians(ang))*20; x1=sx+math.cos(math.radians(ang))*r; y1=sy+math.sin(math.radians(ang))*r
        d.line((x0,y0,x1,y1),fill=(255,196,20,255),width=4)
    d.ellipse((742,47,786,82),fill=(255,255,247,255));d.ellipse((768,38,811,83),fill=(255,255,247,255));d.ellipse((793,52,825,82),fill=(255,255,247,255));d.rounded_rectangle((744,62,825,84),radius=11,fill=(255,255,247,255))
    text(d,(842,62),'22°C',31,(255,255,255,255),anchor='lm',stroke=2,stroke_fill=(0,42,110,170),jp=True)

def cream_row(y):
    # Match the approved warm paper field around the course.
    if y<350: return (247,239,214,255)
    t=max(0,min(1,(y-350)/(1458-350)))
    a=np.array([247,239,214],float);b=np.array([234,220,184],float)
    c=(a*(1-t)+b*t).astype(np.uint8)
    return tuple(c.tolist())+(255,)

def clear_course_window(base):
    # Remove the undersized v1152 course and every old shadow/garbage pixel.
    d=ImageDraw.Draw(base,'RGBA')
    for y in range(350,1458):
        d.line((238,y,700,y),fill=cream_row(y),width=1)

def preserve_geometry_tone(im,hole):
    # Geometry-preserving global tone only. No mask reshape, crop distortion, rotation, or object redraw.
    im=alpha_tight(im)
    if hole in (2,3):
        rgb=im.convert('RGB')
        rgb=ImageEnhance.Color(rgb).enhance(1.08)
        rgb=ImageEnhance.Contrast(rgb).enhance(1.05)
        rgb=ImageEnhance.Sharpness(rgb).enhance(1.10)
        out=rgb.convert('RGBA');out.putalpha(im.getchannel('A'))
        return out
    return im

def paste_course(base,im,hole):
    x0,y0,x1,y1=SAFE[hole]; sw=x1-x0;sh=y1-y0
    im=preserve_geometry_tone(im,hole)
    scale=min(sw/im.width,sh/im.height)
    nw=max(1,round(im.width*scale));nh=max(1,round(im.height*scale))
    im=im.resize((nw,nh),Image.Resampling.LANCZOS)
    x=x0+(sw-nw)//2;y=y0+(sh-nh)//2
    # Shadow is derived from exact alpha and composited inside the same strict safe rect.
    buf=Image.new('RGBA',(sw,sh),(0,0,0,0))
    shadow=Image.new('RGBA',im.size,(0,0,0,0))
    shadow.putalpha(im.getchannel('A').filter(ImageFilter.GaussianBlur(5)).point(lambda v:int(v*.18)))
    buf.alpha_composite(shadow,(x-x0+4,y-y0+6))
    buf.alpha_composite(im,(x-x0,y-y0))
    base.alpha_composite(buf,(x0,y0))
    # Sanity: the composited region can never leave the safe rectangle.
    return (x,y,nw,nh)

sources={1:isolate_h1(),2:exact_h2(),3:exact_h3()}
for hole in (1,2,3):
    fp=RES/f'furano_king_h{hole}_base_v1152.webp'
    if not fp.exists(): raise SystemExit(f'missing generated base {fp}')
    base=Image.open(fp).convert('RGBA')
    if base.size!=(W,H): raise SystemExit(f'base canvas changed: {fp} {base.size}')
    clean_header(base,hole,PAR[hole])
    clear_course_window(base)
    box=paste_course(base,sources[hole],hole)
    # Re-paste nav if present in generated base is intentionally unnecessary: clear window stops at 1457.
    # Keep player panel/wood board/target/nav exactly as generated from the approved master grammar.
    base.save(fp,'WEBP',lossless=True,method=6)
    print('V1153 FIX',hole,'safe',SAFE[hole],'placed',box,'source',sources[hole].size,'out',fp)

# Emit a build marker for the workflow gate.
(RES/'furano_king123_v1153.lock').write_text('FURANO KING H1-H3 REVIEW LOCK\nH2=exact 408_2.webp\nH3=exact 408_3.webp\nstrict safe clip + clean header\n')
