plugins { id 'com.android.application' }

android {
    namespace 'com.vwid.accollector'
    compileSdk 35
    defaultConfig {
        applicationId 'com.vwid.accollector'
        minSdk 23
        targetSdk 28
        versionCode 3
        versionName '1.2-HIDDEN-READONLY'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
