plugins { id 'com.android.application' }

android {
    namespace 'com.vwid.hvaccontrolprobe'
    compileSdk 35
    defaultConfig {
        applicationId 'com.vwid.hvaccontrolprobe'
        minSdk 23
        targetSdk 28
        versionCode 3
        versionName '0.3-CONFIG-TRACE'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
